//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingDojoHelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingDojoHelper.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the Finish Him! time to provide a hard stop for the developer on the keyboard. It&apos;ll be impossible to continue typing if the time is due..
        /// </summary>
        public static string ActivateFinishHimTime {
            get {
                return ResourceManager.GetString("ActivateFinishHimTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The green line was your target time and the other line depicts the time of each of your TDD-cycles..
        /// </summary>
        public static string AllCycleTimes {
            get {
                return ResourceManager.GetString("AllCycleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your average TDD-cycle time so far..
        /// </summary>
        public static string AverageCycleTimeSoFar {
            get {
                return ResourceManager.GetString("AverageCycleTimeSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_Success_Excellent {
            get {
                return ResourceManager.GetStream("Change_Success_Excellent", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_Success_Excellent2 {
            get {
                return ResourceManager.GetStream("Change_Success_Excellent2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_Success_Excellent3 {
            get {
                return ResourceManager.GetStream("Change_Success_Excellent3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_Success_Excellent4 {
            get {
                return ResourceManager.GetStream("Change_Success_Excellent4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_Success_Outstanding {
            get {
                return ResourceManager.GetStream("Change_Success_Outstanding", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_Success_WellDone {
            get {
                return ResourceManager.GetStream("Change_Success_WellDone", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_Success_WellDone2 {
            get {
                return ResourceManager.GetStream("Change_Success_WellDone2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_Success_WellDone3 {
            get {
                return ResourceManager.GetStream("Change_Success_WellDone3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_TooLong_DontMakeMeLaugh {
            get {
                return ResourceManager.GetStream("Change_TooLong_DontMakeMeLaugh", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_TooLong_HahahaDontMakeMeLaugh {
            get {
                return ResourceManager.GetStream("Change_TooLong_HahahaDontMakeMeLaugh", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_TooLong_HahahaYouSuck {
            get {
                return ResourceManager.GetStream("Change_TooLong_HahahaYouSuck", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_TooLong_KahnLaugh {
            get {
                return ResourceManager.GetStream("Change_TooLong_KahnLaugh", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_TooLong_KahnLaugh2 {
            get {
                return ResourceManager.GetStream("Change_TooLong_KahnLaugh2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Change_TooLong_YouAreNothing {
            get {
                return ResourceManager.GetStream("Change_TooLong_YouAreNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TDD-cycle time is the timespan of a full red-green-refactor mantra. Set your target time here and be aware of Shao Khan, who will comment on your achievings!.
        /// </summary>
        public static string DefineCycleTime {
            get {
                return ResourceManager.GetString("DefineCycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set how long your coding dojo-session should last. Preserve at least 5 minutes for a retrospective though..
        /// </summary>
        public static string DefineDojoTime {
            get {
                return ResourceManager.GetString("DefineDojoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the number of combatants. Your overall statistics will be generated according to this number..
        /// </summary>
        public static string DefineNumberOfCombatants {
            get {
                return ResourceManager.GetString("DefineNumberOfCombatants", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_FlawlessVictory {
            get {
                return ResourceManager.GetStream("End_Success_FlawlessVictory", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_FlawlessVictory2 {
            get {
                return ResourceManager.GetStream("End_Success_FlawlessVictory2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_FlawlessVictory3 {
            get {
                return ResourceManager.GetStream("End_Success_FlawlessVictory3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_FlawlessVictory4 {
            get {
                return ResourceManager.GetStream("End_Success_FlawlessVictory4", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_JohnnyCageWins {
            get {
                return ResourceManager.GetStream("End_Success_JohnnyCageWins", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_KanoWins {
            get {
                return ResourceManager.GetStream("End_Success_KanoWins", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_LiuKangWins {
            get {
                return ResourceManager.GetStream("End_Success_LiuKangWins", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_RaidenWins {
            get {
                return ResourceManager.GetStream("End_Success_RaidenWins", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_ScorpionWins {
            get {
                return ResourceManager.GetStream("End_Success_ScorpionWins", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_SonyaWins {
            get {
                return ResourceManager.GetStream("End_Success_SonyaWins", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream End_Success_SubZeroWins {
            get {
                return ResourceManager.GetStream("End_Success_SubZeroWins", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Fight {
            get {
                return ResourceManager.GetStream("Fight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ah, you&apos;re a config-guy. Feel free to customize it to your needs..
        /// </summary>
        public static string GoToAdvancedConfig {
            get {
                return ResourceManager.GetString("GoToAdvancedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your average TDD-cycle time..
        /// </summary>
        public static string ResultingAverageCycleTime {
            get {
                return ResourceManager.GetString("ResultingAverageCycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream RoundOne {
            get {
                return ResourceManager.GetStream("RoundOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string Rounds {
            get {
                return ResourceManager.GetString("Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the key to press when you finished a full TDD-cycle and a new developer takes turn. Let Shao Khan tell you how good or bad your time was..
        /// </summary>
        public static string SelectChangeDeveloperKey {
            get {
                return ResourceManager.GetString("SelectChangeDeveloperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the key to press when you finished the complete code kata or when you think you trained enough..
        /// </summary>
        public static string SelectEndKataKey {
            get {
                return ResourceManager.GetString("SelectEndKataKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You think you&apos;ll make a TDD-cycle in time? Go ahead!.
        /// </summary>
        public static string StartToCode {
            get {
                return ResourceManager.GetString("StartToCode", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream StopIt_FinishHim {
            get {
                return ResourceManager.GetStream("StopIt_FinishHim", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream StopIt_FinishHim2 {
            get {
                return ResourceManager.GetStream("StopIt_FinishHim2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream StopIt_FinishHim3 {
            get {
                return ResourceManager.GetStream("StopIt_FinishHim3", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream StopIt_PrepareToDie {
            get {
                return ResourceManager.GetStream("StopIt_PrepareToDie", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream StopIt_Scream {
            get {
                return ResourceManager.GetStream("StopIt_Scream", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream StopIt_Scream2 {
            get {
                return ResourceManager.GetStream("StopIt_Scream2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream StopIt_YouSuck {
            get {
                return ResourceManager.GetStream("StopIt_YouSuck", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream StopIt_YouWeakPatheticFool {
            get {
                return ResourceManager.GetStream("StopIt_YouWeakPatheticFool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding Dojo Helper.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
    }
}
